# Generated by Django 5.0.4 on 2024-04-14 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossOneself',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время')),
                ('action', models.CharField(max_length=600, verbose_name='действие')),
                ('is_nice', models.BooleanField(default=False, verbose_name='это приятная привычка')),
                ('period', models.SmallIntegerField(default=1, max_length=2, verbose_name='периодичность')),
                ('duration', models.DurationField(verbose_name='длительность')),
                ('is_public', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('place', models.CharField(blank=True, max_length=600, null=True, verbose_name='место')),
                ('prise', models.CharField(blank=True, max_length=300, null=True, verbose_name='вознаграждение')),
                ('chain_nice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooster.crossoneself', verbose_name='вознаграждение-привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
