# Generated by Django 5.0.4 on 2024-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossoneself',
            name='last_run',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего выполнения'),
        ),
        migrations.AlterField(
            model_name='crossoneself',
            name='period',
            field=models.SmallIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
