# Generated by Django 5.0.4 on 2024-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0003_alter_crossoneself_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossoneself',
            name='last_run',
            field=models.DateField(auto_now=True, verbose_name='дата последнего выполнения'),
        ),
    ]
