# Generated by Django 5.0.4 on 2024-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0004_alter_crossoneself_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossoneself',
            name='last_run',
            field=models.DateField(auto_now_add=True, verbose_name='дата последнего выполнения'),
        ),
    ]
