# Generated by Django 5.0.4 on 2024-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooster', '0005_alter_crossoneself_last_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossoneself',
            name='last_run',
        ),
        migrations.AddField(
            model_name='crossoneself',
            name='next_run',
            field=models.DateField(blank=True, null=True, verbose_name='дата следующего выполнения'),
        ),
    ]
